### get access token
POST https://{{host}}/v1/access-token
Content-Type: application/json
Authorization: Basic ZGJjOWQ3NGYtYTE0Yy00YmJhLWIwZjYtNTIwOTJjOTUwMzY3OkdScDJDc1hlNEZZelVzV1U

{
  "grant_type": "client_credentials"
}

### get list bank
GET https://{{host}}/v1/api/bank
Content-Type: application/json
platform: api

